plan:
  description: >
    1. Prioritise the topics you want to cover in the report.
    2. Identify target audience, their interests and their pain points.
    3. Deliver detailed content outline including introduction, key points and call to action.
    4. Include SOE keywords and relevant data and sources
  expected_output: >
    A comprehensive content plan document with an outline, SOE keywords and sources
