gather_sports_news:
  description: >
    Search sports websites and gather information about upcoming horse races in UK on 24th November 2024.
    Use at least 10 different source websites to gather information.
  expected_output: >
    A complete list of races on 24th November 2024.
    Each race must have list of sources with suggested winner and tip justification.
    Each item must include source reference link.
    Each item must include list of odds for all horse for the same race.
  agent: sports_news_gatherer
